name = "SpectralGraphWavelet"
uuid = "3dfa037c-0911-445a-8980-d6a37e5c973e"
authors = ["luke-lowery"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
